params_config:
  # general configs
  model: ["GPNN"] # GPNN
  task_type: ["task_graph"] # task_node, task_graph
  task: ["ogbg-molpcba"]
  # graph task: FRANKENSTEIN, DD, NCI1, NCI109, PROTEINS, IMDB-BINARY, IMDB-MULTI, COLLAB
  # node task: Actor, Cora_geom, CiteSeer_geom, PubMed_geom
  agent_package: [100] # specify the num of works an agent should finish
  ignore_keys: [['seed','index_runs','index_split']]

  # hyper-params for OGB-GNN backbone
  layer_gnn_edge: [5] # for edge feature extraction

  layer_gnn1: [3] # for parsing step in encoder
  layer_gnn2: ['share'] # for pooling step in encoder; if set to "share", GNN2 will share parameter with GNN1; if set to "follow", GNN2 will apply the same layers as GNN1 but don't share parameter with GNN1
  layer_deepsets: [1]
  layer_parsingnet: [1]
  layer_trans: [2]

  hidden_channel: [300]
  dropout_network: [0.3] # for neural networks
  dropout_parsing: [0] # for parsing
  link_ignore_self_loop: [True]
  act_final: [False] # Maybe useful for some datasets, e.g. PROTEINS

  epochs: [200] # maximum epochs
  patience: [20] # early-stopping patience
  log_freq: [1] # metric/loss log frequency
  stop_item: ['loss_val'] # loss_val, metric_val

  learning_rate: [0.001]
  weight_decay: [0]
  grad_norm: ['None'] # grad clipping, None for OGB datasets, 1.0 for others
  lr_scheduler: [False] # use lr scheduler or not, False for OGB datasets

  index_split: [0] # 0~9 for 10-fold split, 0 for fix split
  seed: [0,1,2,3,4,5,6,7,8,9] # if set to "None", do not fix seed
  index_runs: [0]

  # configs for graph tasks
  batch_size: [1024]
  splits: ["OGB"] # ASAP, GMT, OGB

  # configs for node tasks
  layer_gnn3: ['None'] # for un-pooling step in decoder; if set to "share", GNN3 will share parameter with GNN2; if set to "follow", GNN3 will apply the same layers as GNN2 but don't share parameter with GNN2

sweep_config:
  method: "grid"
  metric:
    name: "metric/final"
    goal: "maximize"